server:
  port: 8090
spring:
  datasource:
    databaseName: shop
    portNumber: 5432
    serverName: localhost
    driverClassName: "org.postgresql.Driver"
    jdbcUrl: "jdbc:postgresql://127.0.0.1/store"
    username: postgres
    password: "superpass"
    minimumIdle: 10
    maximumPoolSize: 20
    idleTimeout: 180000
    initializationFailFast: true
    maxLifetime: 1800000
    type: com.zaxxer.hikari.HikariDataSource
jwt:
  jwtSecret: secretkey
  jwtExpirationInMs: 604800000
  origin: http://localhost:3000